# FIXME: Install files

SUBDIRS = growl syncmenu

SRCS = __init__.py	\
       dbus.py		\
       growler.py	\
       prep_py2app.py
# FIXME: Compile C part
#       idle.c		\
#       nsapp.m

include ../../buildsys.mk

all: ${OBJS}
