# FIXME: Install files

SUBDIRS = common traymodule osx

SRCS = adhoc_commands.py		\
       advanced.py			\
       atom_window.py			\
       cell_renderer_image.py		\
       chat_control.py			\
       config.py			\
       conversation_textview.py		\
       dataforms_widget.py		\
       dialogs.py			\
       disco.py				\
       features_window.py		\
       filetransfers_window.py		\
       gajim-remote.py			\
       gajim.py				\
       gajim_themes_window.py		\
       groupchat_control.py		\
       groups.py			\
       gtkexcepthook.py			\
       gtkgui_helpers.py		\
       history_manager.py		\
       history_window.py		\
       htmltextview.py			\
       ipython_view.py			\
       lastfm.py			\
       lastfm_track_listener.py		\
       message_control.py		\
       message_textview.py		\
       message_window.py		\
       music_track_listener.py		\
       negotiation.py			\
       network_manager_listener.py	\
       notify.py			\
       profile_window.py		\
       remote_control.py		\
       roster_window.py			\
       search_window.py			\
       secrets.py			\
       session.py			\
       statusicon.py			\
       systray.py			\
       tooltips.py			\
       vcard.py

include ../buildsys.mk

all: ${OBJS}
