SUBDIRS = doing_chores		\
	  drinking		\
	  eating		\
	  exercising		\
	  grooming		\
	  having_appointment	\
	  inactive		\
	  relaxing		\
	  talking		\
	  traveling		\
	  unknown		\
	  working

# FIXME: Install files

include ../../../buildsys.mk
