name: Python applicationx

on: [push]

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        brew install gtk+3 librsvg pygobject3 adwaita-icon-theme gtksourceview3 gstreamer
        brew install libsoup libsoup@2
        python -m pip install --upgrade pyOpenSSL pyasn1 pyobjc pillow idna precis-i18n certifi css-parser
        python -m pip install git+https://github.com/pyinstaller/pyinstaller.git@develop
        python -m pip install git+https://dev.gajim.org/gajim/python-nbxmpp.git
        python -m pip install .
    - name: Build Mac app
      run: |
        python mac/makebundle.py --version 0.0.1
    - name: Upload app
      uses: actions/upload-artifact@v1
      with:
        name: gajim.dmg
        path: gajim-0.0.1.dmg
